/* Generated By:JJTree: Do not edit this line. ASTAssignOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTAssignOperator extends SimpleNode {
    private int tokenType;
    
    public ASTAssignOperator(int id) {
        super(id);
    }
    
    public ASTAssignOperator(WandParser p, int id) {
        super(p, id);
    }
    
    public int getTokenType( ) {
        return this.tokenType;
    }
    
    public void setTokenType( int type ) {
        this.tokenType = type;
    }
}
/* JavaCC - OriginalChecksum=cf0e61c93fe1650746147004a492d584 (do not edit this line) */
