/* Generated By:JJTree: Do not edit this line. ASTAssertStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTAssertStatement extends SimpleNode {
    public ASTAssertStatement(int id) {
        super(id);
    }

    public ASTAssertStatement(WandParser p, int id) {
        super(p, id);
    }
    
    public WandNode getExpression( ) {
        return (WandNode) jjtGetChild( 0 );
    }
    
    public WandNode getMessage( ) {
        if ( jjtGetNumChildren() < 2 ) {
            return null;
        }
        return (WandNode) jjtGetChild( 1 );
    }


    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=0a27d1954d529e7e702a75ba740eda67 (do not edit this line) */
