/* Generated By:JJTree: Do not edit this line. ASTArrayType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTArrayType extends ASTType {
  public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(WandParser p, int id) {
    super(p, id);
  }
  
  public ASTType getBaseType( ) {
      return (ASTType) jjtGetChild( 0 );
  }
  
  public String getTypeName( ) {
      // FIXME: implement this (this will move to the generator anyway)
      return getBaseType( ).getTypeName( ) + "[]";
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f4c6a62df89277bbba367fc51614dd36 (do not edit this line) */
