/* Generated By:JJTree: Do not edit this line. ASTAssignExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTAssignExpression extends SimpleNode {
  public ASTAssignExpression(int id) {
    super(id);
  }

  public ASTAssignExpression(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59400de393a2f79674b711dc5b963af2 (do not edit this line) */
