/* Generated By:JJTree: Do not edit this line. ASTArrayType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTArrayType extends ASTType {
    public ASTArrayType(int id) {
        super(id);
    }
    
    public ASTArrayType(WandParser p, int id) {
        super(p, id);
    }
    
    public ASTType getBaseType( ) {
        return (ASTType) jjtGetChild( 0 );
    }
    
    public String getTypeName( ) {
        // FIXME: implement this (this will move to the generator anyway)
        return getBaseType( ).getTypeName( ) + "[]";
    }
}
/* JavaCC - OriginalChecksum=cc7f7c434bd16f5bf90fb500f6dc0769 (do not edit this line) */
