/* Generated By:JJTree: Do not edit this line. ASTBuiltinType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTBuiltinType extends SimpleNode {
  public ASTBuiltinType(int id) {
    super(id);
  }

  public ASTBuiltinType(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e3fab5dd7db135aa4f6c234a53a1cd0 (do not edit this line) */
