/* Generated By:JJTree: Do not edit this line. ASTBlockStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTBlockStatements extends SimpleNode {
  public ASTBlockStatements(int id) {
    super(id);
  }

  public ASTBlockStatements(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e4e929b0ea64c04abe8e047fcdbce48 (do not edit this line) */
