/* Generated By:JJTree: Do not edit this line. ASTBuiltinType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTBuiltinType extends ASTType {
  public ASTBuiltinType(int id) {
    super(id);
  }

  public ASTBuiltinType(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0e3dc9a2c2b7fe978ae392ea2f561b2a (do not edit this line) */
