/* Generated By:JJTree: Do not edit this line. ASTCharacterLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTCharacterLiteral extends SimpleNode {
  public ASTCharacterLiteral(int id) {
    super(id);
  }

  public ASTCharacterLiteral(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ddd4a85a600714613f7d8ecbc66a1312 (do not edit this line) */
