/* Generated By:JJTree: Do not edit this line. ASTCastExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTCastExpression extends SimpleNode {
    public ASTCastExpression(int id) {
        super(id);
    }

    public ASTCastExpression(WandParser p, int id) {
        super(p, id);
    }
    
    public ASTType getTypeNode() {
        return (ASTType)jjtGetChild( 0 );
    }
    
    public WandType getWandType() {
        return getTypeNode().getType();
    } 
    
    public WandType getExpressionType() {
        return getWandType();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=60c0f1bd5624ab16a8641c033a8a0ca6 (do not edit this line) */
