/* Generated By:JJTree: Do not edit this line. ASTClassFieldDeclarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTClassFieldDeclarations extends SimpleNode {
  public ASTClassFieldDeclarations(int id) {
    super(id);
  }

  public ASTClassFieldDeclarations(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0054ef907f6dd46f1688b45794029af (do not edit this line) */
