/* Generated By:JJTree: Do not edit this line. ASTClassFieldDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTClassFieldDeclarator extends SimpleNode {
  public ASTClassFieldDeclarator(int id) {
    super(id);
  }

  public ASTClassFieldDeclarator(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3ed8e8e055ecbbecb747fe3e2a0d12f4 (do not edit this line) */
