/* Generated By:JJTree: Do not edit this line. ASTDecoratedFunctionOrClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTDecoratedFunctionOrClassDeclaration extends SimpleNode {
  public ASTDecoratedFunctionOrClassDeclaration(int id) {
    super(id);
  }

  public ASTDecoratedFunctionOrClassDeclaration(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9cf132dad2fe99d8a8ebe1d78a2ba71e (do not edit this line) */
