/* Generated By:JJTree: Do not edit this line. ASTDecoratedFunctionDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTDecoratedFunctionDeclaration extends SimpleNode {
    public ASTDecoratedFunctionDeclaration(int id) {
        super(id);
    }

    public ASTDecoratedFunctionDeclaration(WandParser p, int id) {
        super(p, id);
    }

    public WandNode getFunction( ) {
        return (WandNode) jjtGetChild( 1 );
    }
    
    public WandNode getModifiers( ) {
        return (WandNode) jjtGetChild( 0 );
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=97346bba278d892761bfdf2fe06e3492 (do not edit this line) */
