/* Generated By:JJTree: Do not edit this line. ASTDoWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTDoWhileStatement extends SimpleNode {
    public ASTDoWhileStatement(int id) {
        super(id);
    }

    public ASTDoWhileStatement(WandParser p, int id) {
        super(p, id);
    }
    
    public WandNode getCondition( ) {
        return (WandNode) jjtGetChild( 1 );
    }
    
    public WandNode getLoopBody( ) {
        return (WandNode) jjtGetChild( 0 );
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=ff053d3d63a8d6e2de20a080b34efc41 (do not edit this line) */
