/* Generated By:JJTree: Do not edit this line. ASTFunctionParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTFunctionParameters extends SimpleNode {
  public ASTFunctionParameters(int id) {
    super(id);
  }

  public ASTFunctionParameters(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5f0ad1cfdaf89c07520f27a8618d6f7c (do not edit this line) */
