/* Generated By:JJTree: Do not edit this line. ASTFloatingPointLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTFloatingPointLiteral extends SimpleNode {
  public ASTFloatingPointLiteral(int id) {
    super(id);
  }

  public ASTFloatingPointLiteral(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a696fd3b98e861e952304dc2939d31d (do not edit this line) */
