/* Generated By:JJTree: Do not edit this line. ASTFunctionParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTFunctionParameter extends SimpleNode {
    public ASTFunctionParameter(int id) {
        super(id);
    }
    
    public ASTFunctionParameter(WandParser p, int id) {
        super(p, id);
    }
    
    public WandNode getType( ) {
        return (WandNode) jjtGetChild( 0 );
    }
    
    public WandNode getIdentifier( ) {
        return (WandNode) jjtGetChild( 1 );
    }
    
    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=410b117f0d9ffa623d07a96d2b6f835b (do not edit this line) */
