/* Generated By:JJTree: Do not edit this line. ASTInfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTInfixOperator extends SimpleNode {
  public ASTInfixOperator(int id) {
    super(id);
  }

  public ASTInfixOperator(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e344be05bd0ae6ce6ca3cb17c95fd89 (do not edit this line) */
