/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTIntegerLiteral extends SimpleNode {
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=35f4ae5bb98de94141b200b0030f0d1b (do not edit this line) */
