/* Generated By:JJTree: Do not edit this line. ASTInfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTInfixOperator extends SimpleNode {
    private int operatorType = 0;
    
    public ASTInfixOperator(int id) {
        super(id);
    }
    
    public ASTInfixOperator(WandParser p, int id) {
        super(p, id);
    }
    
    public void setTokenType( int type ) {
        operatorType = type;
    }
    
    public int getOperatorType( ) {
        return operatorType;
    }
    
    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=4532e5a20febe2da746ab085d244d1ba (do not edit this line) */
