/* Generated By:JJTree: Do not edit this line. ASTInfixExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTInfixExpression extends SimpleNode {
  public ASTInfixExpression(int id) {
    super(id);
  }

  public ASTInfixExpression(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cea875bbe3c2d68b4580af6f6e8573b2 (do not edit this line) */
