/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTIfStatement extends SimpleNode {
    public ASTIfStatement(int id) {
        super(id);
    }
    
    public ASTIfStatement(WandParser p, int id) {
        super(p, id);
    }

    public WandNode getCondition( ) {
        return (WandNode) jjtGetChild( 0 );
    }
    
    public WandNode getThenStatement( ) {
        return (WandNode) jjtGetChild( 1 );
    }
    
    public WandNode getElseStatement( ) {
        return (WandNode) jjtGetChild( 2 );
    }


    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=cd4d5e420c8cb457cd7e5103e7a80184 (do not edit this line) */
