/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTLiteral extends ASTExpression {
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b0cc53658cfb289e867e8925e7a7ab0 (do not edit this line) */
