/* Generated By:JJTree: Do not edit this line. ASTLoopStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTLoopStatement extends SimpleNode {
    public ASTLoopStatement(int id) {
        super(id);
    }

    public ASTLoopStatement(WandParser p, int id) {
        super(p, id);
    }

    public WandNode getCondition( ) {
        if ( jjtGetNumChildren() < 2 ) {
            return null;
        }
        return (WandNode) jjtGetChild( 1 );
    }
    
    public WandNode getLoopBody( ) {
        return (WandNode) jjtGetChild( 0 );
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=949146d6692969854897eaf1eb405084 (do not edit this line) */
