/* Generated By:JJTree: Do not edit this line. ASTMulInfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTMulInfixOperator extends SimpleNode {
  public ASTMulInfixOperator(int id) {
    super(id);
  }

  public ASTMulInfixOperator(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ad25208eeed18375dd8f203b3685a799 (do not edit this line) */
