/* Generated By:JJTree: Do not edit this line. ASTNamespaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTNamespaceDeclaration extends SimpleNode {
    public ASTNamespaceDeclaration(int id) {
        super(id);
    }

    public ASTNamespaceDeclaration(WandParser p, int id) {
        super(p, id);
    }
    
    public String getQualifiedName( ) {
        ASTQualifiedNamespaceName qualName = 
            (ASTQualifiedNamespaceName)this.getChild( 0 );
        return qualName.getQualifiedName( );
    }
    
    public String toString( ) {
        return "<ASTNamespaceDeclaration: " + getQualifiedName( ) + ">";
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d250417b0dee76ab878653f35db6470f (do not edit this line) */
