/* Generated By:JJTree: Do not edit this line. ASTNamespaceName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTNamespaceName extends SimpleNode {
    private String name;
    
    public ASTNamespaceName(int id) {
        super(id);
    }

    public ASTNamespaceName(WandParser p, int id) {
        super(p, id);
    }
    
    public void setName( String name ) {
        this.name = name;
    }
    
    public String getName( ) {
        return this.name;
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=7f61334cad8e7992f4ed0780f203d368 (do not edit this line) */
