/* Generated By:JJTree: Do not edit this line. ASTPostfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTPostfixOperator extends SimpleNode {
  public ASTPostfixOperator(int id) {
    super(id);
  }

  public ASTPostfixOperator(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5830d7df5da6364a7742fa0f10a4ecd2 (do not edit this line) */
