/* Generated By:JJTree: Do not edit this line. ASTPostfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTPostfixOperator extends SimpleNode {
  public ASTPostfixOperator(int id) {
    super(id);
  }

  public ASTPostfixOperator(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2dba7f0768b67d097af066f726855878 (do not edit this line) */
