/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTProgram extends SimpleNode {
    public ASTProgram(int id) {
        super(id);
    }
    
    public ASTProgram(WandParser p, int id) {
        super(p, id);
    }
    
    private ASTDeclarations declarations;
    public void setDeclarations( ASTDeclarations declarations ) {
        this.declarations = declarations;
    }

}
/* JavaCC - OriginalChecksum=7b0d917801b31d2c38afb1a55a722f26 (do not edit this line) */
