/* Generated By:JJTree: Do not edit this line. ASTPrefixExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTPrefixExpression extends SimpleNode {
  public ASTPrefixExpression(int id) {
    super(id);
  }

  public ASTPrefixExpression(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9b9e9d3804b65d3ba05d7cf4ee84d6b (do not edit this line) */
