/* Generated By:JJTree: Do not edit this line. ASTPrimary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTPrimary extends SimpleNode {
  public ASTPrimary(int id) {
    super(id);
  }

  public ASTPrimary(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48a6c77b99b51b41e81d041b8d43c1ca (do not edit this line) */
