/* Generated By:JJTree: Do not edit this line. ASTPrefixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTPrefixOperator extends SimpleNode {
  public ASTPrefixOperator(int id) {
    super(id);
  }

  public ASTPrefixOperator(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c59d05268b9deb082af1251d24b493c (do not edit this line) */
