/* Generated By:JJTree: Do not edit this line. ASTQualifiedNamespaceName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTQualifiedNamespaceName extends SimpleNode {
    public ASTQualifiedNamespaceName(int id) {
        super(id);
    }

    public ASTQualifiedNamespaceName(WandParser p, int id) {
        super(p, id);
    }
    
    public String getQualifiedName( ) {
        StringBuilder builder = new StringBuilder( );
        
        for ( WandNode child: this ) {
            ASTNamespaceName name = (ASTNamespaceName)child;
            
            if ( builder.length( ) > 0 ) {
                builder.append( "." );
            }
            
            builder.append( name.getName( ) );
        }
        
        return builder.toString( );
    }
    
    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=9abd86c999ced17e4e070bd7f7d1580b (do not edit this line) */
