/* Generated By:JJTree: Do not edit this line. ASTQualifiedIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTQualifiedIdentifier extends SimpleNode {
  public ASTQualifiedIdentifier(int id) {
    super(id);
  }

  public ASTQualifiedIdentifier(WandParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WandParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=effefd81aac9c780e0cf7d80d605b603 (do not edit this line) */
