/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTStringLiteral extends ASTLiteral {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84560eadf94c257f2cc428c3d55609ec (do not edit this line) */
