/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;
import wand.generators.*;

public
class ASTType extends SimpleNode {
    private String typeName;
    private WandType type;
    
    public ASTType(int id) {
        super(id);
    }
    
    public ASTType(WandParser p, int id) {
        super(p, id);
    }
    
    public Generator getGenerator( ) {
        return GeneratorFactory.getGeneratorFactory( ).getTypeGenerator( );
    }
    
    public String getTypeName( ) {
        return this.typeName;
    }
    
    public void setTypeName( String typeName ) {
        this.typeName = typeName;
    }
    
    public void setType( WandType type ) {
        this.type = type;
    }
    
    public WandType getType( ) {
        return this.type;
    }
    
    public String toString( ) {
        return "<ASTType: " + getTypeName() + ">";
    }

}
/* JavaCC - OriginalChecksum=4229a2d77631ca19e66d4848b4032133 (do not edit this line) */
