/* Generated By:JJTree: Do not edit this line. ASTUsingStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTUsingStatement extends SimpleNode {
    public ASTUsingStatement(int id) {
        super(id);
    }

    public ASTUsingStatement(WandParser p, int id) {
        super(p, id);
    }

    public String getQualifiedName( ) {
        ASTQualifiedNamespaceName qualName = 
            (ASTQualifiedNamespaceName)this.getChild( 0 );
        return qualName.getQualifiedName( );
    }
    
    public String toString( ) {
        return "<ASTUsingStatement: " + getQualifiedName( ) + ">";
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=e97263d2aa79cf91316462757ae9511e (do not edit this line) */
