/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarators.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

public
class ASTVariableDeclarators extends SimpleNode {
  public ASTVariableDeclarators(int id) {
    super(id);
  }

  public ASTVariableDeclarators(WandParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f89d6a2bdfb9807bf3aded3547c1e77 (do not edit this line) */
