/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wand.core.WandNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wand.parser;

import wand.core.*;

public
class ASTWhileStatement extends SimpleNode {
    public ASTWhileStatement(int id) {
        super(id);
    }

    public ASTWhileStatement(WandParser p, int id) {
        super(p, id);
    }

    public WandNode getCondition( ) {
        return (WandNode) jjtGetChild( 0 );
    }
    
    public WandNode getLoopBody( ) {
        return (WandNode) jjtGetChild( 1 );
    }

    /** Accept the visitor. **/
    public Object jjtAccept(WandParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=dcc41475e8099b6f3480c514d2d63960 (do not edit this line) */
