/* Generated By:JavaCC: Do not edit this line. WandParserTreeConstants.java Version 5.0 */
package wand.parser;

public interface WandParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATIONS = 1;
  public int JJTVOID = 2;
  public int JJTFUNCTIONDECLARATION = 3;
  public int JJTFUNCTIONPARAMETERS = 4;
  public int JJTFUNCTIONPARAMETER = 5;
  public int JJTBUILTINTYPE = 6;
  public int JJTARRAYTYPE = 7;
  public int JJTQUALIFIEDIDENTIFIER = 8;
  public int JJTASSIGNEXPRESSION = 9;
  public int JJTINFIXEXPRESSION = 10;
  public int JJTPREFIXEXPRESSION = 11;
  public int JJTPOSTFIXEXPRESSION = 12;
  public int JJTASSIGNOPERATOR = 13;
  public int JJTINFIXOPERATOR = 14;
  public int JJTPREFIXOPERATOR = 15;
  public int JJTPOSTFIXOPERATOR = 16;
  public int JJTINTEGERLITERAL = 17;
  public int JJTFLOATINGPOINTLITERAL = 18;
  public int JJTBOOLEANLITERAL = 19;
  public int JJTNULLLITERAL = 20;
  public int JJTBLOCK = 21;
  public int JJTLOCALVARIABLEDECLARATIONSTATEMENT = 22;
  public int JJTEXPRESSIONSTATEMENT = 23;
  public int JJTVARIABLEDECLARATOR = 24;
  public int JJTIDENTIFIER = 25;


  public String[] jjtNodeName = {
    "Program",
    "Declarations",
    "void",
    "FunctionDeclaration",
    "FunctionParameters",
    "FunctionParameter",
    "BuiltinType",
    "ArrayType",
    "QualifiedIdentifier",
    "AssignExpression",
    "InfixExpression",
    "PrefixExpression",
    "PostfixExpression",
    "AssignOperator",
    "InfixOperator",
    "PrefixOperator",
    "PostfixOperator",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Block",
    "LocalVariableDeclarationStatement",
    "ExpressionStatement",
    "VariableDeclarator",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=fd2684df1f6c5f1502021ae5a37fbd72 (do not edit this line) */
