/* Generated By:JJTree&JavaCC: Do not edit this line. WandParserConstants.java */
package wand.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int FLOAT = 7;
  /** RegularExpression Id. */
  int FPLIT = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int OPENBLOCK = 11;
  /** RegularExpression Id. */
  int CLOSEBLOCK = 12;
  /** RegularExpression Id. */
  int ID = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"void\"",
    "\"int\"",
    "\"float\"",
    "<FPLIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<ID>",
    "\"[\"",
    "\"]\"",
  };

}
