/* Generated By:JavaCC: Do not edit this line. WandParserTreeConstants.java Version 5.0 */
package wand.parser;

public interface WandParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATIONS = 1;
  public int JJTNAMESPACEDECLARATION = 2;
  public int JJTVOID = 3;
  public int JJTUSINGSTATEMENT = 4;
  public int JJTQUALIFIEDNAMESPACENAME = 5;
  public int JJTNAMESPACENAME = 6;
  public int JJTDECORATEDFUNCTIONORCLASSDECLARATION = 7;
  public int JJTDECORATEDFUNCTIONDECLARATION = 8;
  public int JJTDECORATEDCLASSDECLARATION = 9;
  public int JJTMODIFIERS = 10;
  public int JJTMODIFIER = 11;
  public int JJTCLASSDECLARATION = 12;
  public int JJTQUALIFIEDIDENTIFIERLIST = 13;
  public int JJTCLASSFIELDDECLARATIONS = 14;
  public int JJTCLASSFIELDDECLARATOR = 15;
  public int JJTFUNCTIONDECLARATION = 16;
  public int JJTFUNCTIONPARAMETERS = 17;
  public int JJTFUNCTIONPARAMETER = 18;
  public int JJTBUILTINTYPE = 19;
  public int JJTARRAYTYPE = 20;
  public int JJTQUALIFIEDIDENTIFIER = 21;
  public int JJTASSIGNEXPRESSION = 22;
  public int JJTCONDITIONALEXPRESSION = 23;
  public int JJTINFIXEXPRESSION = 24;
  public int JJTUNARYEXPRESSION = 25;
  public int JJTPOSTFIXEXPRESSION = 26;
  public int JJTCASTEXPRESSION = 27;
  public int JJTFUNCTIONCALL = 28;
  public int JJTARGUMENTS = 29;
  public int JJTASSIGNOPERATOR = 30;
  public int JJTINFIXOPERATOR = 31;
  public int JJTUNARYOPERATOR = 32;
  public int JJTPOSTFIXOPERATOR = 33;
  public int JJTINTEGERLITERAL = 34;
  public int JJTFLOATINGPOINTLITERAL = 35;
  public int JJTBOOLEANLITERAL = 36;
  public int JJTNULLLITERAL = 37;
  public int JJTLOCALVARIABLEDECLARATIONSTATEMENT = 38;
  public int JJTBLOCKSTATEMENT = 39;
  public int JJTIFSTATEMENT = 40;
  public int JJTWHILESTATEMENT = 41;
  public int JJTDOWHILESTATEMENT = 42;
  public int JJTLOOPSTATEMENT = 43;
  public int JJTBREAKSTATEMENT = 44;
  public int JJTCONTINUESTATEMENT = 45;
  public int JJTASSERTSTATEMENT = 46;
  public int JJTRETURNSTATEMENT = 47;
  public int JJTEXPRESSIONSTATEMENT = 48;
  public int JJTVARIABLEDECLARATOR = 49;
  public int JJTIDENTIFIER = 50;


  public String[] jjtNodeName = {
    "Program",
    "Declarations",
    "NamespaceDeclaration",
    "void",
    "UsingStatement",
    "QualifiedNamespaceName",
    "NamespaceName",
    "DecoratedFunctionOrClassDeclaration",
    "DecoratedFunctionDeclaration",
    "DecoratedClassDeclaration",
    "Modifiers",
    "Modifier",
    "ClassDeclaration",
    "QualifiedIdentifierList",
    "ClassFieldDeclarations",
    "ClassFieldDeclarator",
    "FunctionDeclaration",
    "FunctionParameters",
    "FunctionParameter",
    "BuiltinType",
    "ArrayType",
    "QualifiedIdentifier",
    "AssignExpression",
    "ConditionalExpression",
    "InfixExpression",
    "UnaryExpression",
    "PostfixExpression",
    "CastExpression",
    "FunctionCall",
    "Arguments",
    "AssignOperator",
    "InfixOperator",
    "UnaryOperator",
    "PostfixOperator",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "LocalVariableDeclarationStatement",
    "BlockStatement",
    "IfStatement",
    "WhileStatement",
    "DoWhileStatement",
    "LoopStatement",
    "BreakStatement",
    "ContinueStatement",
    "AssertStatement",
    "ReturnStatement",
    "ExpressionStatement",
    "VariableDeclarator",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=5dbd9c6036f621fee078b061bb97f1f4 (do not edit this line) */
