/* Generated By:JavaCC: Do not edit this line. WandParserTreeConstants.java Version 5.0 */
package wand.parser;

public interface WandParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATIONS = 1;
  public int JJTVOID = 2;
  public int JJTDECORATEDFUNCTIONDECLARATION = 3;
  public int JJTMODIFIERS = 4;
  public int JJTMODIFIER = 5;
  public int JJTFUNCTIONDECLARATION = 6;
  public int JJTFUNCTIONPARAMETERS = 7;
  public int JJTFUNCTIONPARAMETER = 8;
  public int JJTBUILTINTYPE = 9;
  public int JJTARRAYTYPE = 10;
  public int JJTQUALIFIEDIDENTIFIER = 11;
  public int JJTASSIGNEXPRESSION = 12;
  public int JJTINFIXEXPRESSION = 13;
  public int JJTPREFIXEXPRESSION = 14;
  public int JJTPOSTFIXEXPRESSION = 15;
  public int JJTASSIGNOPERATOR = 16;
  public int JJTINFIXOPERATOR = 17;
  public int JJTPREFIXOPERATOR = 18;
  public int JJTPOSTFIXOPERATOR = 19;
  public int JJTINTEGERLITERAL = 20;
  public int JJTFLOATINGPOINTLITERAL = 21;
  public int JJTBOOLEANLITERAL = 22;
  public int JJTNULLLITERAL = 23;
  public int JJTBLOCK = 24;
  public int JJTLOCALVARIABLEDECLARATIONSTATEMENT = 25;
  public int JJTRETURNSTATEMENT = 26;
  public int JJTEXPRESSIONSTATEMENT = 27;
  public int JJTVARIABLEDECLARATOR = 28;
  public int JJTIDENTIFIER = 29;


  public String[] jjtNodeName = {
    "Program",
    "Declarations",
    "void",
    "DecoratedFunctionDeclaration",
    "Modifiers",
    "Modifier",
    "FunctionDeclaration",
    "FunctionParameters",
    "FunctionParameter",
    "BuiltinType",
    "ArrayType",
    "QualifiedIdentifier",
    "AssignExpression",
    "InfixExpression",
    "PrefixExpression",
    "PostfixExpression",
    "AssignOperator",
    "InfixOperator",
    "PrefixOperator",
    "PostfixOperator",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Block",
    "LocalVariableDeclarationStatement",
    "ReturnStatement",
    "ExpressionStatement",
    "VariableDeclarator",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=33b08bffe59f07e1dc891022290af64e (do not edit this line) */
