/* Generated By:JJTree&JavaCC: Do not edit this line. WandParserConstants.java */
package wand.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 10;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 11;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 12;
  /** RegularExpression Id. */
  int HEX_LITERAL = 13;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 14;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 15;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int OPENBLOCK = 21;
  /** RegularExpression Id. */
  int CLOSEBLOCK = 22;
  /** RegularExpression Id. */
  int OPINC = 23;
  /** RegularExpression Id. */
  int OPDEC = 24;
  /** RegularExpression Id. */
  int OPADD = 25;
  /** RegularExpression Id. */
  int OPSUB = 26;
  /** RegularExpression Id. */
  int OPASSIGN = 27;
  /** RegularExpression Id. */
  int ID = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"void\"",
    "\"int\"",
    "\"float\"",
    "<FLOAT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<BINARY_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "<ID>",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"~\"",
    "\";\"",
    "\",\"",
  };

}
